/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'balanceAmount' : bigint,
  'paymentStatus' : string,
  'propertyType' : string,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'createdAt' : bigint,
  'commission' : bigint,
  'subServiceId' : bigint,
  'advanceAmount' : bigint,
  'totalAmount' : bigint,
  'address' : string,
  'technicianId' : [] | [bigint],
  'notes' : string,
  'quantity' : bigint,
  'customerId' : bigint,
  'paymentReference' : [] | [string],
}
export type BookingStatus = { 'assigned' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export interface Invoice {
  'balanceAmount' : bigint,
  'serviceName' : string,
  'paymentStatus' : string,
  'bookingId' : bigint,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'commission' : bigint,
  'subServiceName' : string,
  'advanceAmount' : bigint,
  'totalAmount' : bigint,
  'address' : string,
  'quantity' : bigint,
}
export type Role = { 'technician' : null } |
  { 'admin' : null } |
  { 'customer' : null };
export interface Service {
  'id' : bigint,
  'pricingType' : string,
  'name' : string,
  'createdAt' : bigint,
  'category' : string,
  'basePrice' : bigint,
}
export interface SubService {
  'id' : bigint,
  'pricingType' : string,
  'name' : string,
  'createdAt' : bigint,
  'serviceId' : bigint,
  'basePrice' : bigint,
}
export interface Technician {
  'id' : bigint,
  'totalCompleted' : bigint,
  'totalAssigned' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'activeStatus' : boolean,
  'phone' : string,
}
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
}
export interface _SERVICE {
  'assignTechnician' : ActorMethod<[bigint, bigint], boolean>,
  'cancelBooking' : ActorMethod<[bigint], boolean>,
  'createBooking' : ActorMethod<
    [bigint, bigint, string, bigint, string, string, string, string],
    Booking
  >,
  'createService' : ActorMethod<[string, string, bigint, string], Service>,
  'createSubService' : ActorMethod<
    [bigint, string, bigint, string],
    SubService
  >,
  'createTechnician' : ActorMethod<[string, string], Technician>,
  'createUser' : ActorMethod<[string, Role], User>,
  'deactivateTechnician' : ActorMethod<[bigint], boolean>,
  'generateInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSubServicesByService' : ActorMethod<[bigint], Array<SubService>>,
  'getTechnicians' : ActorMethod<[], Array<Technician>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'isSeedDone' : ActorMethod<[], boolean>,
  'markFullyPaid' : ActorMethod<[bigint], boolean>,
  'markPayment' : ActorMethod<[bigint, string], boolean>,
  'seedData' : ActorMethod<[], undefined>,
  'seedSubServicesV2' : ActorMethod<[], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];