/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'propertyType' : string,
  'createdAt' : bigint,
  'subServiceId' : bigint,
  'advanceAmount' : bigint,
  'totalAmount' : bigint,
  'quantity' : bigint,
  'customerId' : bigint,
}
export type BookingStatus = { 'assigned' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Role = { 'technician' : null } |
  { 'admin' : null } |
  { 'customer' : null };
export interface Service {
  'id' : bigint,
  'pricingType' : string,
  'name' : string,
  'createdAt' : bigint,
  'category' : string,
  'basePrice' : bigint,
}
export interface SubService {
  'id' : bigint,
  'pricingType' : string,
  'name' : string,
  'createdAt' : bigint,
  'serviceId' : bigint,
  'basePrice' : bigint,
}
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
}
export interface _SERVICE {
  'createBooking' : ActorMethod<[bigint, bigint, string, bigint], Booking>,
  'createService' : ActorMethod<[string, string, bigint, string], Service>,
  'createSubService' : ActorMethod<
    [bigint, string, bigint, string],
    SubService
  >,
  'createUser' : ActorMethod<[string, Role], User>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSubServicesByService' : ActorMethod<[bigint], Array<SubService>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'isSeedDone' : ActorMethod<[], boolean>,
  'seedData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];