/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'paymentStatus' : IDL.Text,
  'propertyType' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'createdAt' : IDL.Int,
  'commission' : IDL.Nat,
  'subServiceId' : IDL.Nat,
  'advanceAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'technicianId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'paymentReference' : IDL.Opt(IDL.Text),
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'pricingType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const SubService = IDL.Record({
  'id' : IDL.Nat,
  'pricingType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'serviceId' : IDL.Nat,
  'basePrice' : IDL.Nat,
});
export const Technician = IDL.Record({
  'id' : IDL.Nat,
  'totalCompleted' : IDL.Nat,
  'totalAssigned' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'activeStatus' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Role = IDL.Variant({
  'technician' : IDL.Null,
  'admin' : IDL.Null,
  'customer' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
});
export const Invoice = IDL.Record({
  'balanceAmount' : IDL.Nat,
  'serviceName' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'bookingId' : IDL.Nat,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'commission' : IDL.Nat,
  'subServiceName' : IDL.Text,
  'advanceAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'assignTechnician' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'createBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Booking],
      [],
    ),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Service],
      [],
    ),
  'createSubService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [SubService],
      [],
    ),
  'createTechnician' : IDL.Func([IDL.Text, IDL.Text], [Technician], []),
  'createUser' : IDL.Func([IDL.Text, Role], [User], []),
  'deactivateTechnician' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSubServicesByService' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SubService)],
      ['query'],
    ),
  'getTechnicians' : IDL.Func([], [IDL.Vec(Technician)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'isSeedDone' : IDL.Func([], [IDL.Bool], ['query']),
  'markPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'seedData' : IDL.Func([], [], []),
  'seedSubServicesV2' : IDL.Func([], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'paymentStatus' : IDL.Text,
    'propertyType' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'createdAt' : IDL.Int,
    'commission' : IDL.Nat,
    'subServiceId' : IDL.Nat,
    'advanceAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'technicianId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'paymentReference' : IDL.Opt(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'pricingType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const SubService = IDL.Record({
    'id' : IDL.Nat,
    'pricingType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'serviceId' : IDL.Nat,
    'basePrice' : IDL.Nat,
  });
  const Technician = IDL.Record({
    'id' : IDL.Nat,
    'totalCompleted' : IDL.Nat,
    'totalAssigned' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'activeStatus' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Role = IDL.Variant({
    'technician' : IDL.Null,
    'admin' : IDL.Null,
    'customer' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
  });
  const Invoice = IDL.Record({
    'balanceAmount' : IDL.Nat,
    'serviceName' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'bookingId' : IDL.Nat,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'commission' : IDL.Nat,
    'subServiceName' : IDL.Text,
    'advanceAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'assignTechnician' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'createBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Booking],
        [],
      ),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Service],
        [],
      ),
    'createSubService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [SubService],
        [],
      ),
    'createTechnician' : IDL.Func([IDL.Text, IDL.Text], [Technician], []),
    'createUser' : IDL.Func([IDL.Text, Role], [User], []),
    'deactivateTechnician' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSubServicesByService' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SubService)],
        ['query'],
      ),
    'getTechnicians' : IDL.Func([], [IDL.Vec(Technician)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'isSeedDone' : IDL.Func([], [IDL.Bool], ['query']),
    'markPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'seedData' : IDL.Func([], [], []),
    'seedSubServicesV2' : IDL.Func([], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };