/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'propertyType' : IDL.Text,
  'createdAt' : IDL.Int,
  'subServiceId' : IDL.Nat,
  'advanceAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'pricingType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const SubService = IDL.Record({
  'id' : IDL.Nat,
  'pricingType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'serviceId' : IDL.Nat,
  'basePrice' : IDL.Nat,
});
export const Role = IDL.Variant({
  'technician' : IDL.Null,
  'admin' : IDL.Null,
  'customer' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [Booking],
      [],
    ),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Service],
      [],
    ),
  'createSubService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [SubService],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, Role], [User], []),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSubServicesByService' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SubService)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'isSeedDone' : IDL.Func([], [IDL.Bool], ['query']),
  'seedData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'propertyType' : IDL.Text,
    'createdAt' : IDL.Int,
    'subServiceId' : IDL.Nat,
    'advanceAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'pricingType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const SubService = IDL.Record({
    'id' : IDL.Nat,
    'pricingType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'serviceId' : IDL.Nat,
    'basePrice' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'technician' : IDL.Null,
    'admin' : IDL.Null,
    'customer' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [Booking],
        [],
      ),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Service],
        [],
      ),
    'createSubService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [SubService],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, Role], [User], []),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSubServicesByService' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SubService)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'isSeedDone' : IDL.Func([], [IDL.Bool], ['query']),
    'seedData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };