/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface User {
    id: bigint;
    name: string;
    createdAt: bigint;
    role: Role;
}
export interface SubService {
    id: bigint;
    pricingType: string;
    name: string;
    createdAt: bigint;
    serviceId: bigint;
    basePrice: bigint;
}
export interface Service {
    id: bigint;
    pricingType: string;
    name: string;
    createdAt: bigint;
    category: string;
    basePrice: bigint;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    paymentStatus: string;
    propertyType: string;
    scheduledDate: string;
    scheduledTime: string;
    createdAt: bigint;
    commission: bigint;
    subServiceId: bigint;
    advanceAmount: bigint;
    totalAmount: bigint;
    address: string;
    technicianId?: bigint;
    notes: string;
    quantity: bigint;
    customerId: bigint;
    paymentReference?: string;
}
export interface Invoice {
    balanceAmount: bigint;
    serviceName: string;
    paymentStatus: string;
    bookingId: bigint;
    scheduledDate: string;
    scheduledTime: string;
    commission: bigint;
    subServiceName: string;
    advanceAmount: bigint;
    totalAmount: bigint;
    address: string;
    quantity: bigint;
}
export interface Technician {
    id: bigint;
    totalCompleted: bigint;
    totalAssigned: bigint;
    name: string;
    createdAt: bigint;
    activeStatus: boolean;
    phone: string;
}
export enum BookingStatus {
    assigned = "assigned",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed",
    inProgress = "inProgress"
}
export enum Role {
    technician = "technician",
    admin = "admin",
    customer = "customer"
}
export interface backendInterface {
    assignTechnician(bookingId: bigint, technicianId: bigint): Promise<boolean>;
    createBooking(customerId: bigint, subServiceId: bigint, propertyType: string, quantity: bigint, scheduledDate: string, scheduledTime: string, address: string, notes: string): Promise<Booking>;
    createService(name: string, category: string, basePrice: bigint, pricingType: string): Promise<Service>;
    createSubService(serviceId: bigint, name: string, basePrice: bigint, pricingType: string): Promise<SubService>;
    createTechnician(name: string, phone: string): Promise<Technician>;
    createUser(name: string, role: Role): Promise<User>;
    deactivateTechnician(technicianId: bigint): Promise<boolean>;
    generateInvoice(bookingId: bigint): Promise<Invoice | null>;
    getBookings(): Promise<Array<Booking>>;
    getServices(): Promise<Array<Service>>;
    getSubServicesByService(serviceId: bigint): Promise<Array<SubService>>;
    getTechnicians(): Promise<Array<Technician>>;
    getUsers(): Promise<Array<User>>;
    isSeedDone(): Promise<boolean>;
    markPayment(bookingId: bigint, referenceId: string): Promise<boolean>;
    seedData(): Promise<void>;
    seedSubServicesV2(): Promise<void>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<boolean>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Invoice as _Invoice, Role as _Role, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignTechnician(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTechnician(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTechnician(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createService(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSubService(arg0: bigint, arg1: string, arg2: bigint, arg3: string): Promise<SubService> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTechnician(arg0: string, arg1: string): Promise<Technician> {
        if (this.processError) {
            try {
                const result = await this.actor.createTechnician(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTechnician(arg0, arg1);
            return result;
        }
    }
    async createUser(arg0: string, arg1: Role): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, to_candid_Role_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_User_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, to_candid_Role_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_User_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateTechnician(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateTechnician(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateTechnician(arg0);
            return result;
        }
    }
    async generateInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInvoice(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInvoice(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return result;
        }
    }
    async getSubServicesByService(arg0: bigint): Promise<Array<SubService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubServicesByService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubServicesByService(arg0);
            return result;
        }
    }
    async getTechnicians(): Promise<Array<Technician>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicians();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicians();
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isSeedDone(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSeedDone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSeedDone();
            return result;
        }
    }
    async markPayment(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPayment(arg0, arg1);
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async seedSubServicesV2(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSubServicesV2();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSubServicesV2();
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_User_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: bigint;
    role: _Role;
}): {
    id: bigint;
    name: string;
    createdAt: bigint;
    role: Role;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n11(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    paymentStatus: string;
    propertyType: string;
    scheduledDate: string;
    scheduledTime: string;
    createdAt: bigint;
    commission: bigint;
    subServiceId: bigint;
    advanceAmount: bigint;
    totalAmount: bigint;
    address: string;
    technicianId: [] | [bigint];
    notes: string;
    quantity: bigint;
    customerId: bigint;
    paymentReference: [] | [string];
}): {
    id: bigint;
    status: BookingStatus;
    paymentStatus: string;
    propertyType: string;
    scheduledDate: string;
    scheduledTime: string;
    createdAt: bigint;
    commission: bigint;
    subServiceId: bigint;
    advanceAmount: bigint;
    totalAmount: bigint;
    address: string;
    technicianId?: bigint;
    notes: string;
    quantity: bigint;
    customerId: bigint;
    paymentReference?: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n3(_uploadFile, _downloadFile, value.status),
        paymentStatus: value.paymentStatus,
        propertyType: value.propertyType,
        scheduledDate: value.scheduledDate,
        scheduledTime: value.scheduledTime,
        createdAt: value.createdAt,
        commission: value.commission,
        subServiceId: value.subServiceId,
        advanceAmount: value.advanceAmount,
        totalAmount: value.totalAmount,
        address: value.address,
        technicianId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.technicianId)),
        notes: value.notes,
        quantity: value.quantity,
        customerId: value.customerId,
        paymentReference: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.paymentReference))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    technician: null;
} | {
    admin: null;
} | {
    customer: null;
}): Role {
    return "technician" in value ? Role.technician : "admin" in value ? Role.admin : "customer" in value ? Role.customer : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "assigned" in value ? BookingStatus.assigned : "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    assigned: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.assigned ? {
        assigned: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    technician: null;
} | {
    admin: null;
} | {
    customer: null;
} {
    return value == Role.technician ? {
        technician: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.customer ? {
        customer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
